language: ruby
cache: bundler
env:
  - COVERAGE=true
rvm:
  - 2.1.3
before_script:
  - cp config/database.yml.mysql config/database.yml
  - bundle exec rake db:create db:migrate
  - bundle exec bowndler update
